### ISSUE TITLE
Port field ignored when exporting RDP files

### ISSUE THREAD

**Issue by a-chaudhari** [kimmknight/remoteapptool#12] opened 2020-02-05 04:49 UTC
I use a non-standard RDP port on my host machine.  Setting the port in the GUI has no effect on the exported RDP file and therefore will not work on the client machine. It works fine if I manually add the port into the RDP file.

**Comment by bmg002** [comment] 2020-02-13 21:07
I just tested this in the bmg version of this (ie my version) and cannot reproduce this issue.  When I look in the exported RDP file when I change the port, it has the new port set.
The port is not stored in the application or the registry, just in the generated .RDP file.  So if you export the .RDP file more than once, it will have the default port each time.  BUT if you open the exported .RDP file in a text editor (such as notepad), it WILL have the new port number stored in it in the line "server port:i:3340".  In my case, I changed the port to 3340 and the line I quoted is copy-pasted from the exported .RDP file.

**Comment by MrBrianGale** [comment] 2020-05-19 14:29
Hello a-chaudhari,

Are you able to reproduce this?  So far I have not been able to reproduce this bug.  Also, is this when exporting using the RemoteAppTool or when publishing to a RAWeb interface or are you making an MSI?

**Comment by connected201** [comment] 2020-05-21 21:39
hi, i have same issue, port not appear after ip! i need to modify manually with notepad rdp file

**Comment by MrBrianGale** [comment] 2020-05-21 21:58
Hello connected201,

Could you provide more details about how you are setting this up?  Are you picking the remoteapp, then selecting it, clicking on "Create Client Connections", leaving it marked as default for all settings EXCEPT for PORT (ie it is RDP, not signed, no gateway, etc)?  I just tried this myself right now and checked off the "edit in notepad" button and when it opens the RDP file in notepad, 3rd from the bottom it has the port I changed it to.
NOTE - this is using my fork, but I didn't make any changes to that portion of the code.

Mostly, I would like to know your process to reproduce this problem because at this time, I am not able to reproduce the problem and I am wondering if it is a combination of things that is causing this to  happen to some people.
Other useful things would be what OS are you using (version, edition)? what app are you making the remoteapp for? does the same thing happen if you try making notepad a remoteapp?

**Comment by connected201** [comment] 2020-05-22 11:31
hi, i have windows 8.1
ap settings:
![image](https://user-images.githubusercontent.com/20506433/82663720-e5756880-9c38-11ea-97e5-728fcff20e96.png)

![image](https://user-images.githubusercontent.com/20506433/82663657-c545a980-9c38-11ea-8f4b-36123b0203f7.png)

here is my settings, but if i will save as .RDP file i will obtain this:
![image](https://user-images.githubusercontent.com/20506433/82663582-9b8c8280-9c38-11ea-9edc-00e3a9f0a391.png)

**Comment by connected201** [comment] 2020-05-22 11:32
i just open app, leave all settings by default, just change port to 443, i don't use RD gateway, i use domain to connect to server

**Comment by MrBrianGale** [comment] 2020-05-22 16:01
That is weird.  I did the exact same thing with notepad, but on Windows 10, and it seemed to work.  As a thought, can I get you to try entering the port and AFTER entering it, click on the "Manually edit RDP file"?  I am wondering if the value is not being saved on exit of the box for some reason.

If that doesn't help, can I get you to try it with my fork of the program:
https://github.com/MrBrianGale/remoteapptool/releases/tag/AdvancedOptions_RDPOnly

I don't think it'll make a difference, but I am working on changes on my fork of the code and it could be this  bug is fixed in my fork while fixing and working on other bugs/features.   One feature in my fork that is not in the parent is the ability to redirect audio in and audio out.  Not recommended to use, but it is in there.

**Comment by connected201** [comment] 2020-05-22 16:30
i tried installer version for windows 10, same problem,

**Comment by MrBrianGale** [comment] 2020-05-22 18:12
When you say same results, do you mean that all of my suggestions gave the same results (try clicking on edit in notepad after clicking on port as well as my fork)?

I am low on ideas on what to try.  I just want to confirm your steps from start to end to make sure I am following the same process:
1 - start remoteapp tool as an administrator
2 - pick an app from the list of ones already in the tool
3 - Click on Create Client Connection
4 - change the port
5 - click on Manually Edit RDP File checkbox
6 - click on Create
7 - give the RDP file a new name (or overwrite an existing one)
8 - click on save
9 - wait for notepad to open
Is that the full process OR am I missing a step?
I tested this on Windows 10 Home and Professional and both seem to generate the RDP file with the port information in it
NOTE - all of my testing is off of my fork of the application.

**Comment by MrBrianGale** [comment] 2020-05-27 20:26
I was just re-looking at your screenshots and you are using an old version.  The latest official release is 5.4.0.0.
My latest version (version 5.4.0.2) should not have the bugs you are indicating.  I think the problem MAY be that you are using an old release.

**Comment by connected201** [comment] 2020-05-27 21:12
Give link to compiled version, i will check it

**Comment by connected201** [comment] 2020-05-27 21:19
i checked https://github.com/MrBrianGale/remoteapptool/releases/tag/AdvancedOptions_RDPOnly
your version add server port!

allow desktop composition:i:1
allow font smoothing:i:1
alternate full address:s:test.com
alternate shell:s:rdpinit.exe
devicestoredirect:s:*
disableremoteappcapscheck:i:1
drivestoredirect:s:*
full address:s:test.com
prompt for credentials on client:i:1
promptcredentialonce:i:0
redirectcomports:i:1
redirectdrives:i:1
remoteapplicationmode:i:1
remoteapplicationname:s:LiberKey
remoteapplicationprogram:s:||LiberKey
### server port:i:2121
span monitors:i:1
use multimon:i:1

**Comment by MrBrianGale** [comment] 2020-05-27 21:28
Nice.  Yeah, my fork of it is the only one I can maintain as I am not listed as a contributor or maintainer on the main project.
So any and all changes that I make need to be on my branch.  I am working on keeping up with the version number and I learned something new today too - the old version (5.3.0.0) doesn't support the port option properly.

I also noticed that this project no longer has a release version available.

I do still watch issues here, but feel free to open issues on my fork as well.

Things I fixed/changed in my fork:
1 - apparently fixed the port number missing on RDP export
2 - better handling of file locking to reduce the chance of failure during file copy (Issue number 3)
3 - added in support for audio in and out redirection.

**Comment by connected201** [comment] 2020-05-27 21:31
good job bro!, thanks for your work! put in release a compiled version!  best regards.

**Comment by MrBrianGale** [comment] 2020-05-27 21:45
Yep, I have a compiled version on my fork.  I cannot put one in this project as I am not a maintainer.
Best I can do is keep my fork going!

**Comment by vbap** [comment] 2020-05-28 06:57
> Yep, I have a compiled version on my fork. I cannot put one in this project as I am not a maintainer.
> Best I can do is keep my fork going!

Yes please! Just checked this today due to custom port issue. Your debug version is working...

**Comment by kimmknight** [comment] 2020-08-14 15:37
Yeah, I'm fairly certain this was fixed in 5.4.0.0 so I'll close this issue and it'll be fixed in the next release (very close). Sorry to those using 5.3.0.0, you'll have to edit the port number using notepad in the meantime :-/

**Closed by kimmknight** 2020-08-14 15:37 UTC

**Comment by connected201** [comment] 2020-08-14 15:41
where we can download latest version? on your page i found only this link http://www.kimknight.net/remoteapptool/remoteapptool5300.zip, but i think, that it's old version, best regards
