### ISSUE TITLE
After updating to win10 v2004 black border appears around windows

### ISSUE THREAD

**Issue by seflerZ** [kimmknight/remoteapptool#51] opened 2021-01-13 09:22 UTC
Hi, I'm doing well until updated to v2004. There're black borders around the windows and sometimes even entire window becomes black. Is it compability problem or v2004 has disabled the remtoeapp feature or my graphic card's driver should get updated?

**Comment by sashaqwert** [comment] 2021-01-15 06:46
I also, but when using H.264, there were black spots when enabling H.264 in gpedit.msc.
As a solution, you can try to completely switch to software rendering, but this will lead to a lot of CPU usage.

**Comment by seflerZ** [comment] 2021-01-22 03:46
> I also, but when using H.264, there were black spots when enabling H.264 in gpedit.msc.
> As a solution, you can try to completely switch to software rendering, but this will lead to a lot of CPU usage.

How to switch rendering model?

**Comment by sashaqwert** [comment] 2021-01-22 07:06
> How to switch rendering model?

You can enable / disable H.264 and other settings in gpedit.msc --> Computer Configuration --> ... --> Remote Desktop services

**Comment by seflerZ** [comment] 2021-01-27 08:05
I've tried every possible switch, but still result in black borders

**Comment by MrBrianGale** [comment] 2021-03-17 16:10
Does the same thing happen if you use the Windows Server RemoteApp?
Just trying to figure out if it is related to the tool (very very unlikely, but it could be the new version of windows added new features to remoteapps that are set strangely by default) or RemoteApps in general.

**Comment by sashaqwert** [comment] 2021-03-18 12:03
This is most likely not a RemoteApp Tool problem.
Perhaps adding image quality settings to the RemoteApp Tool will help.

For me rendering via GPU in RemoteApp works like this:

<details>
  <summary>Very big</summary>
  
  
![1](https://user-images.githubusercontent.com/24974508/111622207-f27fcb80-87f9-11eb-97be-48b702afe71b.png)
![2](https://user-images.githubusercontent.com/24974508/111622213-f3b0f880-87f9-11eb-8765-09ddced06f76.png)



https://user-images.githubusercontent.com/24974508/111622127-dc720b00-87f9-11eb-99ea-af1bbe694b0b.mp4


  
</details>

If you disable H.264, some of these problems remain on Windows 10.

If Windows 10 Server 2004, 20H2 and H.264 is disabled, then Windows 7 client has no problem (but 10 has some)

**Comment by seflerZ** [comment] 2021-03-22 10:32
So this seems to be a bug from Microsoft? I've no Windows Server, so I can not replay this on that environment.

**Comment by sashaqwert** [comment] 2021-03-22 13:17
This Microsoft bug or not can only be found on Windows Server 2022.
I have not tested it. I have Windows 10 20H2 with RDP Wrapper.

**Comment by seflerZ** [comment] 2021-03-29 11:54
So what can we do now? Just watch it and wait?

**Comment by sashaqwert** [comment] 2021-04-04 09:10
I am currently unable to install the original RDP on Windows Server 2022 Insider.
<details>
  <summary>Screenshot (Russian language)</summary>
 
![Standart RDP Server 2022](https://user-images.githubusercontent.com/24974508/113504070-66caa680-953e-11eb-9c11-74f6443036bb.png)
 
  
</details>

I tried to test in a virtual machine.

Exit: wait for the release in June - July 2021.

**Comment by sashaqwert** [comment] 2021-04-04 10:06
I have installed RemoteApp Tool.
Since this is a virtual machine, I cannot test H.264.

RemoteApps work, but some have black borders. Context menus appear black for half a second, then display normally. The context menu of the language bar is always black. (as on Windows 10 20H1, 20H2 without H.264).

<details>
  <summary>Screenshots (Russian language)</summary>
 
![Windows Server RemoteApp-1](https://user-images.githubusercontent.com/24974508/113505300-8d8cdb00-9546-11eb-90da-af28b79a752a.png)
![Windows Server RemoteApp-2 language Panel](https://user-images.githubusercontent.com/24974508/113505301-8e257180-9546-11eb-93b1-0f01d925753a.png)
![Windows Server RemoteApp-3 Select app dialog](https://user-images.githubusercontent.com/24974508/113505302-8ebe0800-9546-11eb-9f03-ab851658939b.png)



 

</details>

**Comment by seflerZ** [comment] 2021-04-28 13:03
@sashaqwert I managed to solved this problem by disabling the "Advance RemoteFX Graphics", which resides in "Group Policy Editor (gpedit.msc) under Computer Configuration -> Administrative Templates -> Windows Components -> Remote Desktop Services -> Remote Desktop Session Host -> Remote Session Environment"

Thank God!

**Comment by sashaqwert** [comment] 2021-04-29 11:53
@seflerZ A solution has been found for most RemoteApps, which means you can close the Issue, adding information about known issues to the FAQ.

This change will most likely break some of the RemoteApps for me, since they use OpenGL (for example, DOSBox with scaling enabled)

**Closed** 2021-04-30 08:11 UTC

**Comment by serefarikan** [comment] 2022-05-13 06:22
Just came here to confirm that the workaround suggested by @seflerZ works when remoteApp is used on a Windows 10 professional host and the same OS is the client. Let me drop a few hints for future googlers: black borders around context menus go away when use of advanced remotefx graphics is disabled. Thanks for sharing the workaround @seflerZ .

**Comment by Aster-the-Med-Stu** [comment] 2022-09-04 01:33
Came across the same problem on Win 11 Build 22621.382 today. I guess that Microsoft is deprecating RemoteFX or didn't do thorough testing on normal Windows, as you couldn't add new RemoteFX graphics adapters to virtual machines in Hyper-V.

For the OpenGL problem mentioned by @sashaqwert, enabling "Use hardware graphics adapters for all Remote Desktop Services sessions" in gpedit.msc should be enough for OpenGL apps.

![Krita running with native OpenGL](https://user-images.githubusercontent.com/32929636/188293304-50a75fcd-a914-4396-a142-e7bd48891394.png)

**Comment by seflerZ** [comment] 2022-09-04 12:04
@Aster-the-Med-Stu The lastest Windows Server 2022 also has this issue. I don't think engineering in Microsoft is such a mess. Probably it's related to the changes since WDDM 2.7 which starts to suport GPU-PV (win10 v2004 is the first version starts supporting GPU-PV). Maybe they have made a big change and are so hard to make a fully compatible evolution in a short time. Since Microsoft has given up the Big Bang developing process, I think it's reasonable for themselves at least. I've reported this in TechNet forum. Hop it will be solved in next major release.

**Comment by Neustradamus** [comment] 2024-01-22 01:02
@ all: What is the status of this issue?

**Comment by MrBrianGale** [comment] 2024-01-22 02:05
> @ all: What is the status of this issue?

No status on this. This is NOT a bug with the RemoteAppTool. Hence the issue is closed.
This is a bug with Windows and how it supports things across a remote desktop connection and remote app connection. Same protocol, but different presentation layer. It MAY be fixed in newer versions of Windows (Windows 11 for example).
