### ISSUE TITLE
File transfer is not working in apps

### ISSUE THREAD

**Issue by kahisfz** [kimmknight/remoteapptool#46] opened 2020-09-30 15:17 UTC
Hi, we have a customize database driven application, work fine locally and  in RDP desktops, but when we use it as rdp app tool , file transfer is not working. We can not transfer local file to remote server with our app.
Your kind help is requested

**Comment by MrBrianGale** [comment] 2020-09-30 16:13
This is by design of RemoteApps - the App is running Remotely (hence the name "Remote App").
The remote app has no access to the local machine as it is running entirely server side.  The only thing running client side is "mstsc.exe" which is the Microsoft terminal server client used to connect to a remote machine.
In the scope of the Remote App, "local files" are ones stored on the server, not stored on the client machine.

You can confirm this by starting a remote app session of Notepad (for example) and saving it to your desktop.  When you look at the desktop on your local machine, there will be no file.  If you look on the server, the file will be there.

Closing this as it is working as designed.

**Closed by MrBrianGale** 2020-09-30 16:13 UTC
