### ISSUE TITLE
New RemoteApp (advanced) crashes on save

### ISSUE THREAD

**Issue by kimmknight** [kimmknight/remoteapptool#1] opened 2019-09-29 13:49 UTC
![2200470254-Image 006](https://user-images.githubusercontent.com/45035595/65833435-bc077580-e313-11e9-94ad-9d9318c0f648.png)

To repeat: (Use Windows 10 not 7 or 8)

File > New RemoteApp (advanced)...
Browse to FreeMind.exe
Change short and full name to "FreeMind"
Save
!CRASH!

**Comment by bmg002** [comment] 2019-10-23 20:49
I have a Windows 10 machine and just tried this and was not able to reproduce the bug you reported.
![image](https://user-images.githubusercontent.com/1385604/67432751-0e028a80-f5a4-11e9-8056-d702bb9c7185.png)
As you can see in my screenshot, my settings appear identical to what is in your screenshot and when I hit save, it saves successfully.
I would recommend checking if you have .NET updates that need to be installed.  I am running a fully patched (as of October 23rd, 2019) Windows 10 PC.
Failing that, can you post the entirety of the details section of the error you got?  The little snippet you provided doesn't give quite enough detail to debug.

**Comment by kimmknight** [comment] 2019-10-28 02:33
Thanks for checking. That's interesting, I've had the problem on three different (up-to-date) editions of Windows 10 I've tried today (Professional, Home, Education). I used the Windows Problem Steps Recorder to capture the problem as it occurs (attached) and also put the full error text into a text file (also attached).

[New RemoteApp (advanced) crashes on save-PSR-2019-10-28.zip](https://github.com/kimmknight/remoteapptool/files/3776869/New.RemoteApp.advanced.crashes.on.save-PSR-2019-10-28.zip)
[New RemoteApp (advanced) crashes on save-PSR-2019-10-28.txt](https://github.com/kimmknight/remoteapptool/files/3776870/New.RemoteApp.advanced.crashes.on.save-PSR-2019-10-28.txt)

**Comment by bmg002** [comment] 2019-10-28 14:12
As a thought, are you running this as administrator (right-click run as administrator)?  I am not positive if that is required, but it is a step I take as the application needs to modify registry settings, so it does require elevated permissions.
If that does NOT help, have you tried building it from source?  I had some issues with getting it to save advanced settings when I was putting in an RD Gateway.  Building from source corrected this issue.

I also realized I didn't follow your steps 100%.  I had clicked on the PLUS to create the remoteapp and then the properties tab to modify it.  going to re-test with the new remoteapp (advanced) method.  I have a thought on how to correct it based on the error text you sent (thanks for that).  Going to do some digging and testing.

**Comment by bmg002** [comment] 2019-10-28 15:37
This should be fixed with the commit I am suggesting.
The bug came up because it was trying to modify an object that didn't exist.  Changing it so it looks at the window name (a trick that was used previously) to determine if it is a modified remoteapp or a new remoteapp seems to correct the issue.
The problem was not limited to just windows 10, but to all OS's.  It only appears if you rename the remoteapp while using the new remoteapp (advanced) function.

**Comment by bmg002** [comment] 2019-11-01 13:58
I imagine this issue is now good to close?

**Closed** 2019-11-01 16:15 UTC
Labels: bug
