### ISSUE TITLE
Initiate new session so the current user is not logged off

### ISSUE THREAD

**Issue by Industry** [kimmknight/remoteapptool#106] opened 2024-01-15 02:09 UTC
Every time I launch a program from a machine that is logged in, it asks me to kick off the user. Is there any way to run applications in a different profile / user space?

I tried creating a second account, "RemoteApp" and logging into that, but it still kicks me off. I've also tried using the following settings to no avail:
```
administrative session:i:1
alternate shell:s:1.exe
```

**Comment by MrBrianGale** [comment] 2024-01-15 18:18
This is how RDP sessions work. It is not a bug in the RemoteApp tool.
You are logging into a remote system to run a remote app. Based on what you said, the remote system only allows 1 user connection. Even if you are running the app under a different profile/user space, the OS only allows 1 connection, so the currently logged in user must be removed from the session.
The administrative session SHOULD allow you to have 2 sessions at once on SOME windows OS's (can't remember if they all allow it or not).

This is by design of Remote Desktop and is not something that can be circumvented by the RemoteAppTool. That is not what this tool is designed for. Now, there ARE ways around this, but I am not going to recommend them as they MAY violate the Windows license agreements.

Closing this issue with comment as this is by design of Remote Desktop and not a limitation/issue of RemoteAppTool.

**Closed as completed by MrBrianGale** 2024-01-15 18:18 UTC
