### ISSUE TITLE
Remoteapptool Display Error

### ISSUE THREAD

**Issue by oo00Liang00oo** [kimmknight/remoteapptool#121] opened 2024-06-13 02:53 UTC
The System displays correctly when not using the remoteapptool, but the display becomes worse when using the remoteapptool。
Is there a problem with using remoteapptool on Windows Server 2022 Standard?
I found a similar description on the Microsoft website, please refer to the link below。

https://jpwinsup.github.io/blog/2023/09/12/RemoteDesktopService/RemoteAppActiveWindow/

Environment:Windows Server 2022 Standard,Windows11

Occasion of occurrence:
System has EXEs such as A, B, C, D, E, etc...
 A. EXE's AForm call B. EXE's BForm，BForm Open B EXE's CForm, when CForm is closed,AForm will be displayed at the forefront。
The correct situation should be that BFORM is displayed at the front。
C.EXE D.EXE and E.EXE  also have this problem。
B，C，D，E， Different functions developed by different companies。
To solve this problem, I can only deploy the System on the client computer, which greatly increases maintenance costs。

Can your fix this problem?

**Comment by MrBrianGale** [comment] 2024-06-14 20:21
This is not a bug or enhancement that is possible with Remoteapptool. This is how the remote desktop protocol works with remote apps and/or how your app works when being run as a remote app.

My recommended solution is to rewrite your app to be remote app aware and to bring certain windows (not applications) to focus on close. You MAY get better experience if you use a different RDP client that supports remote apps, but as for which app to use, I can't say for sure as I have not run into this situation as I have not used remote apps that call other apps like that.

To reiterate, this is not a bug with remoteapptool and there is nothing that can be done in remoteapptool to correct or change this behavior. You will need to modify your process such as not having a.exe open b.exe and instead have multiple remote apps configured for A, B, C, D, E and so on and have your end users open the app they need (may or may not be possible), change the code-behind all your EXE's to be a single application with different forms so you can call the correct one to focus on window close, or use a different RDP client application.

I am closing this issue as there is no work to be done.

**Closed by MrBrianGale** 2024-06-14 20:21 UTC
