### ISSUE TITLE
rdp login and remoteapptool login is different

### ISSUE THREAD

**Issue by ericxin1982** [kimmknight/remoteapptool#56] opened 2021-04-20 03:30 UTC
Hi,

I set up my explorer to see My PC instead of quick access, and then I have a seamless explorer opening, and I found my explorer does not have the latest setting. I am wondering the login from remoteapptool seamless is different from rdp, is it right?

How to make the setting I did in rdp, and remoteapptool seamless get update properly, what I should pay attention to?

Thanks
Eric X

**Comment by MrBrianGale** [comment] 2021-04-20 22:17
Every time I tested remoteapps, it was running as "me" on the remote system.
What I EXPECT is happening is that you are changing settings on your local machine and then starting the remote app and not seeing the same settings on the remote app which is the expected outcome.
The remote app will run as the user who started it (unless specified in the remote app to connect as a different user) BUT the remote app runs on the remote server.  So any changes you do locally are NOT applied across the connection.
ALSO if you are currently logged into the server (disconnected state counts here), your profile folder will be locked and you will be logged in with a temporary profile on the server which, if I remember correctly, runs with the same settings as the DEFAULT user (don't quote me on that part though).

Personally, though, I do not see the benefit of having "My PC" as a remote app when you can just set up a share on the remote system OR if you are an admin on the remote system, you can use the administrative share.

**Comment by ericxin1982** [comment] 2021-04-21 02:31
Yes, I am using rdpwrap, and that is not a personal pc, I did not switch from remote me and local me.
I set it up and log off and remotely connect to this rdp/seamless server through my name again, and I found my explorer I have to set again. This is the case I encountered. I may record a video and share to you.
By the way, what is the temp profile you talked about? Where is it?

**Comment by MrBrianGale** [comment] 2021-04-21 14:09
I am not certain what or how RDPWrap works, but I wouldn't be surprised if it is causing some inconsistencies.
As for having to set up explorer again, what I would do is log into the server with a secondary account, start up task manager and look at who things are running as.  This won't help with temp profiles, but it'll help you determine who is running what.
As for temporary profiles, these are things Windows creates when the user profile is unable to be used in a read/write manner (usually because you are already logged in).  They are cleaned up automatically at logoff time, but if you go to C:\users\ you will see a temporary profile.
It would also not surprise me if you are starting "explorer.exe" via remote apps that some things may not load in the correct order.  What I mean is the exe may start before some required user processes or configuration loading such as the registry.  I know the registry loads successfully or things like Excel as a remote app wouldn't work, but I am wondering if something is loading out of order or loading incorrectly.  That being said, while the remote app is running, if you SEE a C:\user\*TEMP* folder being created that wasn't there before, that'd be the temporary profile which would VERY likely be causing the problems you are seeing.

**Comment by sashaqwert** [comment] 2021-04-29 13:24
RDP Wrapper does not create temporary profiles.
The video shows how I launched explorer via PowerShell from a RemoteApp session. At the same time, there was a parallel regular session on the PC under the same user.

<details>
  <summary>Video</summary>
  
  

https://user-images.githubusercontent.com/24974508/116556911-a484da00-a906-11eb-93ca-56b44fe086fc.mp4


  
</details>

As you can see: the "My Computer" section opens correctly (if specified in the registry or through the GUI)

**Comment by ericxin1982** [comment] 2021-05-05 03:21
@sashaqwert 
![image](https://user-images.githubusercontent.com/9047436/117093530-cd3c2200-ad93-11eb-9bce-da7da2ba49b9.png)
The curiosity is here, your console session set open explorer to view my pc, but seamless remoteapp session(same user name) to open explorer, this setting is not updated, that is the concern.
You can try. Temp profile or not that is not the point.

**Comment by sashaqwert** [comment] 2021-05-05 06:25
No problems for me

<details>
  <summary>Video</summary>
  
  

https://user-images.githubusercontent.com/24974508/117103762-95c57980-ad83-11eb-8098-e63b5acb8070.mp4


  
</details>

Without closing the RemoteApp session, I changed the setting for fast access and for my computer.
On the RemoteApp session, all changes were applied instantly.

**Comment by MrBrianGale** [comment] 2022-02-02 17:49
I was reviewing the videos and I have to agree with sashaqwert - the problem is not with Remoteapp, but with something related to your setup.
Now, I agree it MIGHT not be due to temporary profiles, but it very well could be as well.  I know RDPWrap doesn't create temporary profiles, but Windows will if it is unable to get read/write access to %UserProfile%.  It is EASY to test if you are connected to a full user profile or a temporary user profile by going to to the folder %UserProfile%.  If it is C:\Users\<username>, it is a full profile.  If it is anything else, it is likely a temporary profile.
Temporary profiles use the "DEFAULT" profile settings and are cleaned up on logoff.
Temporary profiles are USUALLY created if a single user has 2 active sessions on a machine using 2 different methods such as direct RDP and RemoteApp.
That being said, Windows Server, if I remember right, can be configured to not save the user profile.  That is, the profile is created at logon based on the default profile and is removed at logoff.  So any changes you perform would be lost.

Either way, this "problem" is not a problem with RemoteApp, but is a problem with how you have things configured or how things are being used and there is no work for anyone to do on the RemoteAppTool.  Therefore, I am closing this issue.

**Closed by MrBrianGale** 2022-02-02 17:49 UTC
