### ISSUE TITLE
slow connection speed mstsc

### ISSUE THREAD

**Issue by wwwhyimsobad** [kimmknight/remoteapptool#98] opened 2023-11-24 02:39 UTC
Hello i was using RemoteAppTool for about a year on windows 10 to windows 10 system

Now i made a new connection: from windows 10 to windows server 2022 and after i got image of the app that i connect it just freeze, i cant select anything inside of the app and etc. I download a NetLimiter to see is it even connected to a server and it getting only 50b\s of in and out traffic

how can i fix that?

**Comment by MrBrianGale** [comment] 2023-11-24 14:12
Slow network speeds are not related to this tool. If things are slow, that would be due to your internet speeds or the network connection between your machine and the server.
Best bet would be to look at the network speeds between your machine and the server.

The remoteapptool just creates everything server side so that the server can accept an RDP request to an application. It uses the standard Microsoft remote app stuff in the backend. Therefore any slowness is NOT caused by the tool, but is caused by your network.

Now, troubleshooting steps that I would take is to RDP into the windows server 2022 machine and try running the remote app from there. If performance is improved, it could be that the app doesn't support remote app. The next step I would try is to start the remote app and then RDP into the server and watch task manager to see what's happening as it could be something is causing problems with the RDP session. I would also look at TEMPORARILY disabling any firewalls between the windows 10 machine and the server 2022 machine so you can rule out firewall issues. If it is firewall issues, you'll need to open up firewall ports. Not likely firewall, but I never rule something out until I have tested it. I've seen all sorts of odd things like that before...

As this issue is not a problem with the remote app tool, I am going to close the issue.

**Closed by MrBrianGale** 2023-11-24 14:12 UTC

**Comment by wwwhyimsobad** [comment] 2024-01-04 16:41
[So what i was talking about](https://youtu.be/egYAMFrUKEQ)

rdp connection to server works perfectly but when i try to connect to same server using RemoteApp it just stuck

**Comment by MrBrianGale** [comment] 2024-01-04 17:18
To me that looks like expected behavior. SOME apps (mostly apps that are graphic intense or rely on a non-virtualized GPU or apps that have multiple windows for the main application) will not work as a remote app.
That bug is nothing to do with "slow connection speed", that is completely to do with steam not supporting remote apps. Even if you were able to log into steam, you won't be able to play any games over a remote connection (RDP or remoteapp) as you have no GPU access.

Now a second guess as to why that happens is that you have 2 active sessions to the server - one through RDP and one through remoteapp (I see in the video you only minimized the RDP session, not logged off). Steam MAY be getting confused about where to send the screen updates as you have 2 sessions running under the same account (presumably).
On top of that, running Steam on Windows Server 2022 MAY not be a supported configuration for the application.

All in all, I do not see any evidence that the problem is not with the remote app tool, it is with your specific setup. Remote Apps have limitations that MAY cause problems with some applications too such as user path variables do not work with them. You must use the absolute path reference. RemoteApps are part of the Remote Desktop protocol built by Microsoft.  My guess is that Steam doesn't support remote apps. Like I said above, not all apps support remote apps. Not all apps support remote desktop either.
